//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWEB.Ferretero.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbClase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbClase()
        {
            this.tbTipoProducto = new HashSet<tbTipoProducto>();
        }
    
        public int IdClase { get; set; }
        public string NombreClase { get; set; }
        public int IdCategoria { get; set; }
    
        public virtual tbCategoria tbCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTipoProducto> tbTipoProducto { get; set; }
    }
}
