//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWEB.Ferretero.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbVenta()
        {
            this.tbVentaDetalle = new HashSet<tbVentaDetalle>();
        }
    
        public int IdVenta { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime FechaVenta { get; set; }
    
        public virtual tbCliente tbCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbVentaDetalle> tbVentaDetalle { get; set; }
    }
}
